services:
  web:
    container_name: 'qode-web'
    image: 'qode-web'
    restart: always
    networks:
      - qode-network
    ports:
      - "80:80"
      - "443:443"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./https:/https 
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=Qode;Username=${DB_USERNAME};Password=${DB_PASSWORD};
      ASPNETCORE_URLS: https://+;http://+
      ASPNETCORE_HTTPS_PORTS: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/qode.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${SSL_PASSWORD}

  postgres:
    image: postgres
    restart: always
    networks:
      - qode-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: Qode

networks:
  qode-network:
    driver: bridge
